### ISSUE TITLE
Choppy after invoking reachability???

### ISSUE THREAD

**Issue by rweichler** [rweichler/cylinder#63]
http://www.reddit.com/r/cylinder/comments/2s9xwg/invoke_sb_reachability_causes_cylinder_to_become/

**Comment by blandman** [comment]
I am experiencing this too.

**Comment by rweichler** [comment]
If anyone is experiencing this and is willing to give me full root SSH access so I can diagnose it, let me know.

**Comment by neta540** [comment]
Still happens on 6S+, bug takes effect on iOS 9 and 10 as well.

**Comment by rweichler** [comment]
Cant reproduce anymore
