### ISSUE TITLE
1.0.5 breaks some effects on iOS 8.4

### ISSUE THREAD

**Issue by bluestarstudios** [rweichler/cylinder#72]
Hi!

Glad to see updates being pushed to the tweak! Unfortunately 1.0.5 seems to have some bug that breaks some effects on iOS 8.4, including Dominoes, Foosball and Roadrunner. The effect starts correctly but then the icons of the following page don't animate, just all appear at once after a second.

**Comment by rweichler** [comment]
fixed.
