### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by sgkznj** [rweichler/cylinder#75]
![image](https://user-images.githubusercontent.com/39222931/52426561-42661180-2b0f-11e9-99f0-af79fe93f1ad.png)

**Comment by sgkznj** [comment]
*facepalm*,I understood what my mistake was

**Comment by rweichler** [comment]
@sgkznj What was the mistake?

**Comment by sgkznj** [comment]
I did not specify a file path

**Comment by rweichler** [comment]
@sgkznj What? This build process should work without specifying any file paths. Can you elaborate?

**Comment by sgkznj** [comment]
😅 iI don’t know

Friday, 8 February 2019, 9:23 PM +0300 from notifications@github.com  <notifications@github.com>:

**Comment by ryannair05** [comment]
How did you fix it? @sgkznj  getting the same message aswell
